package ventanas;

import clases.ImagenFondo;

public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        dskEscritorio.setBorder(new ImagenFondo());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAFN = new javax.swing.JMenu();
        miAFNBasico = new javax.swing.JMenuItem();
        miAFNUnir = new javax.swing.JMenuItem();
        miConcatenarAFN = new javax.swing.JMenuItem();
        miAFNCerraduraPositiva = new javax.swing.JMenuItem();
        miAFNCerraduraKleene = new javax.swing.JMenuItem();
        miAFNOpcional = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hernández Rodríguez Armando Giovanni");
        setMaximumSize(new java.awt.Dimension(1477, 830));
        setMinimumSize(new java.awt.Dimension(1477, 830));
        setPreferredSize(new java.awt.Dimension(1190, 669));
        setResizable(false);
        setSize(new java.awt.Dimension(1477, 830));

        javax.swing.GroupLayout dskEscritorioLayout = new javax.swing.GroupLayout(dskEscritorio);
        dskEscritorio.setLayout(dskEscritorioLayout);
        dskEscritorioLayout.setHorizontalGroup(
            dskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1470, Short.MAX_VALUE)
        );
        dskEscritorioLayout.setVerticalGroup(
            dskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 0, 102));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N

        menuAFN.setBackground(new java.awt.Color(255, 255, 255));
        menuAFN.setText("AFN");
        menuAFN.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N

        miAFNBasico.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        miAFNBasico.setText("Básico");
        miAFNBasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAFNBasicoActionPerformed(evt);
            }
        });
        menuAFN.add(miAFNBasico);

        miAFNUnir.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        miAFNUnir.setText("Unir");
        miAFNUnir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAFNUnirActionPerformed(evt);
            }
        });
        menuAFN.add(miAFNUnir);

        miConcatenarAFN.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        miConcatenarAFN.setText("Concatenar");
        miConcatenarAFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConcatenarAFNActionPerformed(evt);
            }
        });
        menuAFN.add(miConcatenarAFN);

        miAFNCerraduraPositiva.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        miAFNCerraduraPositiva.setText("Cerradura +");
        miAFNCerraduraPositiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAFNCerraduraPositivaActionPerformed(evt);
            }
        });
        menuAFN.add(miAFNCerraduraPositiva);

        miAFNCerraduraKleene.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        miAFNCerraduraKleene.setText("Cerradura *");
        miAFNCerraduraKleene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAFNCerraduraKleeneActionPerformed(evt);
            }
        });
        menuAFN.add(miAFNCerraduraKleene);

        miAFNOpcional.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        miAFNOpcional.setText("Opcional");
        miAFNOpcional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAFNOpcionalActionPerformed(evt);
            }
        });
        menuAFN.add(miAFNOpcional);

        jMenuBar1.add(menuAFN);

        jMenu2.setText("Análisis Sintáctico");
        jMenu2.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAFNCerraduraKleeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAFNCerraduraKleeneActionPerformed
        intFrameCerraduraKleene abrirVentana = new intFrameCerraduraKleene();
        dskEscritorio.add(abrirVentana);
        abrirVentana.show();
    }//GEN-LAST:event_miAFNCerraduraKleeneActionPerformed

    private void miAFNOpcionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAFNOpcionalActionPerformed
        intFrameOpc abrirVentana = new intFrameOpc();
        dskEscritorio.add(abrirVentana);
        abrirVentana.show();
    }//GEN-LAST:event_miAFNOpcionalActionPerformed

    private void miAFNBasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAFNBasicoActionPerformed
        intFrameAFNBasico abrirVentana = new intFrameAFNBasico();
        dskEscritorio.add(abrirVentana);
        abrirVentana.show();
    }//GEN-LAST:event_miAFNBasicoActionPerformed

    private void miAFNUnirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAFNUnirActionPerformed
        intFrameUnirAFN abrirVentana = new intFrameUnirAFN();
        dskEscritorio.add(abrirVentana);
        abrirVentana.show();
    }//GEN-LAST:event_miAFNUnirActionPerformed

    private void miConcatenarAFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConcatenarAFNActionPerformed
        intFrameConcatenar abrirVentana = new intFrameConcatenar();
        dskEscritorio.add(abrirVentana);
        abrirVentana.show();
    }//GEN-LAST:event_miConcatenarAFNActionPerformed

    private void miAFNCerraduraPositivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAFNCerraduraPositivaActionPerformed
        intFrameCerraduraPos abrirVentana = new intFrameCerraduraPos();
        dskEscritorio.add(abrirVentana);
        abrirVentana.show();
    }//GEN-LAST:event_miAFNCerraduraPositivaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskEscritorio;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAFN;
    private javax.swing.JMenuItem miAFNBasico;
    private javax.swing.JMenuItem miAFNCerraduraKleene;
    private javax.swing.JMenuItem miAFNCerraduraPositiva;
    private javax.swing.JMenuItem miAFNOpcional;
    private javax.swing.JMenuItem miAFNUnir;
    private javax.swing.JMenuItem miConcatenarAFN;
    // End of variables declaration//GEN-END:variables
}
