/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.util.Set;
import javax.swing.JOptionPane;

public class intFrameUnirAFN extends javax.swing.JInternalFrame {

    public intFrameUnirAFN() {
        initComponents();
        
        intFrameAFNBasico ventana = new intFrameAFNBasico();
        Set<String> keys = ventana.AFNBasicos.keySet();
        for(String key : keys){
            cmbAFN1.addItem(key);
            cmbAFN2.addItem(key);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbAFN1 = new javax.swing.JComboBox<>();
        cmbAFN2 = new javax.swing.JComboBox<>();
        btnUnirAFN = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Unir AFNs");

        btnUnirAFN.setBackground(new java.awt.Color(102, 0, 153));
        btnUnirAFN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUnirAFN.setForeground(new java.awt.Color(255, 255, 255));
        btnUnirAFN.setText("Unir");
        btnUnirAFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirAFNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(cmbAFN1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(cmbAFN2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btnUnirAFN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAFN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAFN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(btnUnirAFN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnirAFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirAFNActionPerformed
        intFrameAFNBasico ventana = new intFrameAFNBasico();
        
        String AFN1key = (String)cmbAFN1.getSelectedItem();
        String AFN2key = (String)cmbAFN2.getSelectedItem();
        ventana.AFNBasicos.get(AFN1key).unirAFN(ventana.AFNBasicos.get(AFN2key));
        JOptionPane.showMessageDialog(this, "Los autómatas se han unido", "Unión de AFNs",JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        
    }//GEN-LAST:event_btnUnirAFNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUnirAFN;
    private javax.swing.JComboBox<String> cmbAFN1;
    private javax.swing.JComboBox<String> cmbAFN2;
    // End of variables declaration//GEN-END:variables
}
