/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author argio
 */
public class intFrameCerraduraPos extends javax.swing.JInternalFrame {

    /**
     * Creates new form intFrameCerraduraPos
     */
    public intFrameCerraduraPos() {
        initComponents();
        intFrameAFNBasico ventana = new intFrameAFNBasico();
        Set<String> keys = ventana.AFNBasicos.keySet();
        for(String key : keys){
            cmbAFN.addItem(key);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbAFN = new javax.swing.JComboBox<>();
        btnCerraduraPositiva = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cerradura Positiva o Transitiva AFN");

        btnCerraduraPositiva.setBackground(new java.awt.Color(102, 0, 153));
        btnCerraduraPositiva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCerraduraPositiva.setForeground(new java.awt.Color(255, 255, 255));
        btnCerraduraPositiva.setText("Obtener");
        btnCerraduraPositiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerraduraPositivaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(btnCerraduraPositiva, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbAFN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(cmbAFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnCerraduraPositiva, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerraduraPositivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerraduraPositivaActionPerformed
        intFrameAFNBasico ventana = new intFrameAFNBasico();
        
        String AFN1key = (String)cmbAFN.getSelectedItem();
        ventana.AFNBasicos.get(AFN1key).cerrPos();
        JOptionPane.showMessageDialog(this, "Se ha obtenenido la Cerradura Positiva +", "Cerradura Positiva AFN",JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_btnCerraduraPositivaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerraduraPositiva;
    private javax.swing.JComboBox<String> cmbAFN;
    // End of variables declaration//GEN-END:variables
}
